// 'use client'

/* css import */
import style from '/src/style/common.module.scss';
import '/src/style/global.scss';
import '/src/style/theme.scss';

/* page import */
import FooterLayout from './components/layout/footer';
import HeaderLayout from './components/layout/header';
import SideNavLayout from './components/layout/sideNav';

// metadata를 컴포넌트 외부에서 정의합니다.
const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export { metadata }; // metadata를 내보냅니다.

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div id="wrap">
      <HeaderLayout />
      <main className={style.bodyWrap}>
        <SideNavLayout />
        {children} {/* 이 부분이 각 페이지별로 변경될 컴포넌트 */}
      </main>
      <FooterLayout />
    </div>
  )
}