// 'use client'

/* css import */
import '/src/style/global.scss';
import '/src/style/theme.scss';

/* page import */

// metadata를 컴포넌트 내부에서 정의합니다.
const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children, // will be a page or nested layout
}: {
  children: React.ReactNode
}) {
  return (
    <div id="wrapPage">
        {children} {/* 이 부분이 각 페이지별로 변경될 컴포넌트 */}
    </div>
  )
}

// metadata는 여기서 사용됩니다.
console.log(metadata);